// Edge cases for the differential test (scripts/diffTest.mjs): each one is
// run through the trainer's engine and through real bash + GNU tools.

const T = 'apple 3\nBanana 10\ncherry 2\napple 3\nbanana 7\nerror: disk 42\nERROR: net 5';
const CSV = 'name,dept,salary\nalice,eng,100\nbob,sales,80\ncarol,eng,120\ndave,ops,80\neve,sales,95';
const LOG = 'INFO start\nERROR disk full\nWARN retry\nERROR timeout\n\nDEBUG done';
const SPACED = '  x  1\nb 2\n  a   3\nc  10';
const PASSWD = 'root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nalice:x:1000:1000:Alice:/home/alice:/bin/zsh';

export const diffCases = [
    // regex dialects
    [T, "grep 'apple|cherry'"],
    [T, "grep 'apple\\|cherry'"],
    [T, "grep -E 'apple|cherry'"],
    [T, "grep '[[:digit:]]0'"],
    [T, "grep '[[:upper:]]'"],
    [T, "grep 'a\\{2\\}'"],
    [T, "grep -E 'p{2}'"],
    [T, "grep 'p+'"],
    [T, "grep -E 'p+l'"],
    [T, "grep '^[a-c]'"],
    [T, "grep 'e$'"],
    [T, "grep -x 'apple 3'"],
    [T, "grep -w 'apple'"],
    [T, "grep -o '[0-9]*'"],
    [T, "grep -on 'an'"],
    [T, "grep -c -i error"],
    [T, "grep -F 'r:'"],
    [T, "grep -m 2 a"],
    [T, "grep -e apple -e cherry"],
    [T, "grep -v -e a -e e"],
    [T, "grep '\\<an'"],
    [T, "grep 'a.*3'"],
    [T, "grep '*'"],
    [T, "grep '[]]'"],
    // sed
    [T, "sed 's/a/A/'"],
    [T, "sed 's/a/A/g'"],
    [T, "sed 's/a/A/2'"],
    [T, "sed 's/a/A/2g'"],
    [T, "sed 's/\\(a\\)\\(p\\)/\\2\\1/'"],
    [T, "sed -E 's/([a-z]+) ([0-9]+)/\\2 \\1/'"],
    [T, "sed 's/[0-9]*$/<&>/'"],
    [T, "sed 's|a|/|g'"],
    [T, "sed -n '2,4p'"],
    [T, "sed '2,3s/a/A/'"],
    [T, "sed '/apple/,/cherry/d'"],
    [T, "sed -n '/error/p;/ERROR/p'"],
    [T, "sed -e '1d' -e 's/ /_/'"],
    [T, "sed '$d'"],
    [T, "sed -n '$p'"],
    [T, "sed '3q'"],
    [T, "sed -n '/a/='"],
    [T, "sed '/a/!d'"],
    [T, "sed 's/A/x/I'"],
    [T, "sed 's/ /\\n/'"],
    [T, "sed -n 's/apple/APPLE/p'"],
    // sort
    [T, 'sort'],
    [T, 'sort -f'],
    [T, 'sort -r'],
    [T, 'sort -u'],
    [T, 'sort -k2 -n'],
    [T, 'sort -k2n'],
    [T, 'sort -k2 -rn'],
    [T, 'sort -k2nr'],
    [T, 'sort -u -k1,1'],
    [CSV, "sort -t',' -k3 -n"],
    [CSV, "sort -t',' -k3 -rn"],
    [CSV, "sort -t',' -k2,2 -k3,3n"],
    [CSV, "sort -t, -k2"],
    [SPACED, 'sort'],
    [SPACED, 'sort -b'],
    [SPACED, 'sort -k2'],
    [SPACED, 'sort -k2b'],
    [SPACED, 'sort -n -k2'],
    [LOG, 'sort | uniq -c | sort -rn'],
    // counting / slicing
    [T, 'grep zzz | wc -l'],
    [T, 'wc'],
    [T, 'wc -l'],
    [T, 'wc -w'],
    [T, 'wc -c'],
    [T, 'wc -lw'],
    [T, 'head -3'],
    [T, 'head -n -2'],
    [T, 'head -c 12'],
    [T, 'tail -2'],
    [T, 'tail -n +5'],
    [T, 'tail +6'],
    [T, 'tail -c 8'],
    // fields
    [CSV, "cut -d',' -f1,3"],
    [CSV, "cut -d, -f2-"],
    [CSV, 'cut -c1-3'],
    [CSV, "cut -d',' -f2 | sort | uniq -c"],
    [LOG, "cut -d' ' -f2"],
    [LOG, "cut -d' ' -f2 -s"],
    [PASSWD, "cut -d: -f1,7"],
    [PASSWD, "awk -F: '{print $1, $NF}'"],
    [PASSWD, "awk -F: '$3 >= 1000 {print $1}'"],
    [CSV, "awk -F, 'NR > 1 {s += $3} END {print s / (NR - 1)}'"],
    [CSV, "awk -F, '$2 ~ /^e/ {print $1}'"],
    [CSV, "awk -F, '$2 !~ /s/'"],
    [T, "awk '{print $2 / 3}'"],
    [T, "awk '{print NR \": \" $0}'"],
    [T, "awk 'END {print NR}'"],
    [T, "awk '{print $1, $2 * 2}'"],
    [T, "awk '/apple/ {n++} END {print n}'"],
    [T, 'awk "{print $1}"'],
    [T, "awk '{print $(NF-1)}'"],
    [SPACED, "awk '{print $2}'"],
    // tr / rev / paste / nl / cat
    [T, "tr 'a-z' 'A-Z'"],
    [T, "tr '[:lower:]' '[:upper:]'"],
    [T, "tr -d '0-9'"],
    [T, "tr -cd 'a-z\\n'"],
    [T, "tr -s 'p'"],
    [T, "tr '\\n' ','"],
    [T, "tr ' ' '\\n'"],
    [SPACED, "tr -s ' '"],
    [T, 'rev'],
    [T, 'tac'],
    [T, "paste -sd','"],
    [T, "paste -sd',;'"],
    [T, 'paste - -'],
    [T, "cut -d' ' -f2 | paste -sd+"],
    [LOG, 'nl'],
    [LOG, 'nl -ba'],
    [LOG, 'cat -n'],
    [LOG, 'cat -b'],
    [LOG, 'cat -s'],
    // shell quoting
    [T, 'grep "apple 3"'],
    [T, 'grep apple\\ 3'],
    [CSV, "cut -d$',' -f1"],
    [T, 'grep -c ""'],
    // errors on both sides
    [T, "sed 's/(a)(p)/\\2\\1/'"],
    [T, "grep '[:alpha:]'"],
    [T, 'grep a missing.txt'],
    [T, 'cut -f'],
    [T, "cut -d'ab' -f1"],
    [T, 'sort -t, -k0'],
    [T, 'head -n abc'],
];
