// Edge cases for the differential test (scripts/diffTest.mjs): each one is
// run through the trainer's engine and through real bash + GNU tools.

const T = 'apple 3\nBanana 10\ncherry 2\napple 3\nbanana 7\nerror: disk 42\nERROR: net 5';
const CSV = 'name,dept,salary\nalice,eng,100\nbob,sales,80\ncarol,eng,120\ndave,ops,80\neve,sales,95';
const LOG = 'INFO start\nERROR disk full\nWARN retry\nERROR timeout\n\nDEBUG done';
const SPACED = '  x  1\nb 2\n  a   3\nc  10';
const PASSWD = 'root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nalice:x:1000:1000:Alice:/home/alice:/bin/zsh';

export const diffCases = [
    // regex dialects
    [T, "grep 'apple|cherry'"],
    [T, "grep 'apple\\|cherry'"],
    [T, "grep -E 'apple|cherry'"],
    [T, "grep '[[:digit:]]0'"],
    [T, "grep '[[:upper:]]'"],
    [T, "grep 'a\\{2\\}'"],
    [T, "grep -E 'p{2}'"],
    [T, "grep 'p+'"],
    [T, "grep -E 'p+l'"],
    [T, "grep '^[a-c]'"],
    [T, "grep 'e$'"],
    [T, "grep -x 'apple 3'"],
    [T, "grep -w 'apple'"],
    [T, "grep -o '[0-9]*'"],
    [T, "grep -on 'an'"],
    [T, "grep -c -i error"],
    [T, "grep -F 'r:'"],
    [T, "grep -m 2 a"],
    [T, "grep -e apple -e cherry"],
    [T, "grep -v -e a -e e"],
    [T, "grep '\\<an'"],
    [T, "grep 'a.*3'"],
    [T, "grep '*'"],
    [T, "grep '[]]'"],
    // sed
    [T, "sed 's/a/A/'"],
    [T, "sed 's/a/A/g'"],
    [T, "sed 's/a/A/2'"],
    [T, "sed 's/a/A/2g'"],
    [T, "sed 's/\\(a\\)\\(p\\)/\\2\\1/'"],
    [T, "sed -E 's/([a-z]+) ([0-9]+)/\\2 \\1/'"],
    [T, "sed 's/[0-9]*$/<&>/'"],
    [T, "sed 's|a|/|g'"],
    [T, "sed -n '2,4p'"],
    [T, "sed '2,3s/a/A/'"],
    [T, "sed '/apple/,/cherry/d'"],
    [T, "sed -n '/error/p;/ERROR/p'"],
    [T, "sed -e '1d' -e 's/ /_/'"],
    [T, "sed '$d'"],
    [T, "sed -n '$p'"],
    [T, "sed '3q'"],
    [T, "sed -n '/a/='"],
    [T, "sed '/a/!d'"],
    [T, "sed 's/A/x/I'"],
    [T, "sed 's/ /\\n/'"],
    [T, "sed -n 's/apple/APPLE/p'"],
    // sort
    [T, 'sort'],
    [T, 'sort -f'],
    [T, 'sort -r'],
    [T, 'sort -u'],
    [T, 'sort -k2 -n'],
    [T, 'sort -k2n'],
    [T, 'sort -k2 -rn'],
    [T, 'sort -k2nr'],
    [T, 'sort -u -k1,1'],
    [CSV, "sort -t',' -k3 -n"],
    [CSV, "sort -t',' -k3 -rn"],
    [CSV, "sort -t',' -k2,2 -k3,3n"],
    [CSV, "sort -t, -k2"],
    [SPACED, 'sort'],
    [SPACED, 'sort -b'],
    [SPACED, 'sort -k2'],
    [SPACED, 'sort -k2b'],
    [SPACED, 'sort -n -k2'],
    [LOG, 'sort | uniq -c | sort -rn'],
    // counting / slicing
    [T, 'grep zzz | wc -l'],
    [T, 'wc'],
    [T, 'wc -l'],
    [T, 'wc -w'],
    [T, 'wc -c'],
    [T, 'wc -lw'],
    [T, 'head -3'],
    [T, 'head -n -2'],
    [T, 'head -c 12'],
    [T, 'tail -2'],
    [T, 'tail -n +5'],
    [T, 'tail +6'],
    [T, 'tail -c 8'],
    // fields
    [CSV, "cut -d',' -f1,3"],
    [CSV, "cut -d, -f2-"],
    [CSV, 'cut -c1-3'],
    [CSV, "cut -d',' -f2 | sort | uniq -c"],
    [LOG, "cut -d' ' -f2"],
    [LOG, "cut -d' ' -f2 -s"],
    [PASSWD, "cut -d: -f1,7"],
    [PASSWD, "awk -F: '{print $1, $NF}'"],
    [PASSWD, "awk -F: '$3 >= 1000 {print $1}'"],
    [CSV, "awk -F, 'NR > 1 {s += $3} END {print s / (NR - 1)}'"],
    [CSV, "awk -F, '$2 ~ /^e/ {print $1}'"],
    [CSV, "awk -F, '$2 !~ /s/'"],
    [T, "awk '{print $2 / 3}'"],
    [T, "awk '{print NR \": \" $0}'"],
    [T, "awk 'END {print NR}'"],
    [T, "awk '{print $1, $2 * 2}'"],
    [T, "awk '/apple/ {n++} END {print n}'"],
    [T, 'awk "{print $1}"'],
    [T, "awk '{print $(NF-1)}'"],
    [SPACED, "awk '{print $2}'"],
    // tr / rev / paste / nl / cat
    [T, "tr 'a-z' 'A-Z'"],
    [T, "tr '[:lower:]' '[:upper:]'"],
    [T, "tr -d '0-9'"],
    [T, "tr -cd 'a-z\\n'"],
    [T, "tr -s 'p'"],
    [T, "tr '\\n' ','"],
    [T, "tr ' ' '\\n'"],
    [SPACED, "tr -s ' '"],
    [T, 'rev'],
    [T, 'tac'],
    [T, "paste -sd','"],
    [T, "paste -sd',;'"],
    [T, 'paste - -'],
    [T, "cut -d' ' -f2 | paste -sd+"],
    [LOG, 'nl'],
    [LOG, 'nl -ba'],
    [LOG, 'cat -n'],
    [LOG, 'cat -b'],
    [LOG, 'cat -s'],
    // shell quoting
    [T, 'grep "apple 3"'],
    [T, 'grep apple\\ 3'],
    [CSV, "cut -d$',' -f1"],
    [T, 'grep -c ""'],
    // errors on both sides
    [T, "sed 's/(a)(p)/\\2\\1/'"],
    [T, "grep '[:alpha:]'"],
    [T, 'grep a missing.txt'],
    [T, 'cut -f'],
    [T, "cut -d'ab' -f1"],
    [T, 'sort -t, -k0'],
    [T, 'head -n abc'],

    // ---- awk: the full language ----
    [T, "awk '{c[$1]++} END {for (k in c) print k, c[k]}' | sort"],
    [CSV, "awk -F, 'NR > 1 {s[$2] += $3} END {for (d in s) printf \"%-6s %5.1f\\n\", d, s[d]}' | sort"],
    [T, "awk '{printf \"%s=%05.2f|%x|%e\\n\", $1, $2, $2 * 10, $2}'"],
    [T, "awk '{print toupper($1), tolower($1), length($1), substr($1, 2, 3), index($1, \"an\")}'"],
    [T, "awk '{n = split($0, a, \"a\"); print n, a[1]}'"],
    [T, "awk '{gsub(/a/, \"<&>\"); print}'"],
    [T, "awk '{sub(/[0-9]+/, \"#\"); print}'"],
    [T, "awk 'match($0, /[0-9]+/) {print RSTART, RLENGTH, substr($0, RSTART, RLENGTH)}'"],
    [T, "awk '{if ($2 > 5) print $1, \"big\"; else if ($2 > 2) print $1, \"mid\"; else print $1, \"small\"}'"],
    [T, "awk 'BEGIN {for (i = 1; i <= 5; i++) s = s i; print s}'"],
    [T, "awk 'BEGIN {i = 3; while (i--) print i; do { j++ } while (j < 4); print j}'"],
    [T, "awk '!seen[$1]++'"],
    [T, "awk 'NR == 2, NR == 4'"],
    [T, "awk '/cherry/, /banana/ {print NR}'"],
    [T, "awk '{$2 = \"X\"; print; print NF}'"],
    [T, "awk -v OFS=- '{$1 = $1; print}'"],
    [T, "awk '{NF = 1; print}'"],
    [T, "awk -v n=3 'NR <= n'"],
    [T, "awk 'function sq(x) {return x * x} {print sq($2)}'"],
    [T, "awk 'function f(a, k) {a[\"x\"] = k} BEGIN {f(arr, 5); print arr[\"x\"]}'"],
    [T, "awk '{print ($2 > 5 ? \"hi\" : \"lo\"), $2 % 3, 2 ^ 3, -2 ^ 2, int(-3.7)}'"],
    [T, "awk 'BEGIN {print 1e6, 1e16, 0.1 + 0.2, 100 / 3, 2 ^ 53, 1 / 7 * 7}'"],
    [T, "awk 'BEGIN {x[1,2] = 3; for (k in x) {split(k, p, SUBSEP); print p[1], p[2]}; if ((1,2) in x) print \"yes\"}'"],
    [T, "awk '$1 ~ \"^[a-c]\"'"],
    [T, "awk 'END {print $0, NF}'"],
    [T, "awk 'NR % 2 {next} {print}'"],
    [T, "awk '{print > \"out.txt\"} END {close(\"out.txt\"); while (0) print}'; cat out.txt"],
    [T, "awk '{print $1 | \"sort -r\"}'"],
    [T, "awk '{print $1 | \"sort\"} END {print \"done\"}'"],
    [T, "awk 'BEGIN {printf \"%c%c%c\\n\", 72, \"i!\", 33}'"],
    [T, "awk '{s = s $2 \",\"} END {sub(/,$/, \"\", s); print s}'"],
    [T, "awk 'BEGIN {exit 3} END {print \"end\"}'; echo $?"],
    [T, "awk '{delete a; a[$1]; n = 0; for (k in a) n++; print n}'"],
    [T, "awk '{print length()}'"],
    ["a:b:c\nd:e:f", "awk -F: '{print $2}'"],
    ["a1b2c\nx9y", "awk -F'[0-9]' '{print $2, NF}'"],
    ["para one\nline two\n\npara two", "awk 'BEGIN {RS = \"\"} {print NR \": \" $1}'"],

    // ---- grep: context, files, recursion ----
    [LOG, 'grep -A1 ERROR'],
    [LOG, 'grep -B1 -n ERROR'],
    [LOG, 'grep -C1 WARN'],
    [LOG, 'grep -A1 -m1 ERROR'],
    ['a\nx\nb\nc\nd\nx\ne\nf\ng\nh\nx', 'grep -C1 x'],
    ['', 'grep -c ERROR app.log web.log', { 'app.log': LOG + '\n', 'web.log': 'GET /\nERROR 500\n' }],
    ['', 'grep -l ERROR *.log', { 'app.log': LOG + '\n', 'web.log': 'GET /\n', 'db.log': 'ERROR x\n' }],
    ['', 'grep -L ERROR *.log', { 'app.log': LOG + '\n', 'web.log': 'GET /\n' }],
    ['', 'grep -n ERROR app.log web.log', { 'app.log': LOG + '\n', 'web.log': 'ERROR 500\n' }],
    ['', 'grep -h ERROR *.log', { 'app.log': LOG + '\n', 'web.log': 'ERROR 500\n' }],
    ['', 'grep -r ERROR logs | sort', { 'logs/app.log': LOG + '\n', 'logs/old/web.log': 'ERROR 500\n', 'notes.txt': 'ERROR?\n' }],
    ['', 'grep -rc ERROR . | sort', { 'logs/app.log': LOG + '\n', 'notes.txt': 'no\n' }],
    ['', 'grep ERROR logs', { 'logs/app.log': 'x\n' }],
    ['', 'grep -q ERROR app.log && echo found', { 'app.log': LOG + '\n' }],
    ['', 'grep -q zzz app.log || echo none', { 'app.log': LOG + '\n' }],
    ['', 'grep ERROR app.log missing.log; echo "status $?"', { 'app.log': LOG + '\n' }],
    ['', 'grep -s ERROR missing.log; echo "status $?"'],

    // ---- sort / uniq / files ----
    ['1K\n2M\n512\n3G\n1.5K\n900', 'sort -h'],
    ['1K\n2M\n512\n3G\n1.5K\n900', 'sort -hr'],
    ['v1.10\nv1.2\nv1.9\nv2.0\nv1.2.1', 'sort -V'],
    ['file10.txt\nfile2.txt\nfile1.txt\nfile1.log', 'sort -V'],
    ['a 10M\nb 2K\nc 1G', 'sort -k2h'],
    [T, 'sort -o sorted.txt; cat sorted.txt'],
    [T, 'sort -c'],
    ['a\nb\nc', 'sort -c && echo sorted'],
    ['', 'sort a.txt b.txt', { 'a.txt': 'pear\napple\n', 'b.txt': 'fig\nbanana\n' }],
    ['', 'sort nope.txt'],
    ['', 'uniq -c in.txt', { 'in.txt': 'a\na\nb\n' }],
    ['', 'uniq in.txt out.txt; cat out.txt', { 'in.txt': 'a\na\nb\n' }],

    // ---- head / tail / wc / cat on files ----
    ['', 'head -2 a.txt b.txt', { 'a.txt': '1\n2\n3\n', 'b.txt': 'x\ny\n' }],
    ['', 'tail -n 1 a.txt b.txt', { 'a.txt': '1\n2\n3\n', 'b.txt': 'x\ny\n' }],
    ['', 'head -q -n1 a.txt b.txt', { 'a.txt': '1\n2\n', 'b.txt': 'x\n' }],
    ['', 'wc -l a.txt b.txt', { 'a.txt': '1\n2\n3\n', 'b.txt': 'x\ny\n' }],
    ['', 'wc a.txt', { 'a.txt': 'one two\nthree\n' }],
    ['', 'wc -l a.txt', { 'a.txt': '1\n2\n3\n' }],
    ['', 'wc -w *.txt', { 'a.txt': 'one two\n', 'b.txt': 'three four five\n', 'c.txt': '' }],
    ['', 'wc -L a.txt', { 'a.txt': 'short\na longer line\n' }],
    ['', 'wc -l < a.txt', { 'a.txt': '1\n2\n3\n' }],
    ['', 'cat a.txt b.txt', { 'a.txt': 'A\n', 'b.txt': 'B\n' }],
    ['', 'cat -n a.txt b.txt', { 'a.txt': 'A\nA2\n', 'b.txt': 'B\n' }],
    ['', 'cat a.txt missing.txt', { 'a.txt': 'A\n' }],
    ['', 'cat -A t.txt', { 't.txt': 'a\tb\n' }],
    ['stdin line', 'cat - a.txt', { 'a.txt': 'A\n' }],
    ['', 'tac a.txt b.txt', { 'a.txt': '1\n2\n', 'b.txt': 'x\ny\n' }],
    ['', 'nl a.txt b.txt', { 'a.txt': '1\n2\n', 'b.txt': 'x\n' }],

    // ---- redirections, sequencing, globs ----
    [T, 'sort > out.txt; wc -l out.txt'],
    [T, 'grep apple > a.txt; grep banana >> a.txt; cat a.txt'],
    ['', 'sort < in.txt', { 'in.txt': 'b\na\n' }],
    ['', 'sort in.txt > in.txt; cat in.txt', { 'in.txt': 'b\na\n' }],
    ['', 'grep x missing.txt 2> /dev/null; echo "status $?"'],
    ['', 'grep x missing.txt 2> err.txt; wc -l < err.txt'],
    ['', 'cat a.txt missing.txt > all.txt 2>&1; wc -l < all.txt', { 'a.txt': 'A\n' }],
    ['', 'cat missing.txt &> out.txt; grep -c No out.txt'],
    ['', 'echo hi >&2 2> /dev/null; echo ok'],
    ['', 'ls'],
    ['', 'ls', { 'b.txt': '', 'a.log': '', 'logs/x.log': '' }],
    ['', 'ls logs', { 'logs/x.log': '', 'logs/y.log': '', 'z': '' }],
    ['', 'ls -F', { 'b.txt': '', 'logs/x.log': '' }],
    ['', 'ls *.log', { 'b.txt': '', 'a.log': '', 'c.log': '' }],
    ['', 'ls logs b.txt', { 'b.txt': '', 'logs/x.log': '' }],
    ['', 'ls nothing.txt'],
    ['', 'ls *.csv'],
    ['', 'cat *.txt | sort', { 'a.txt': 'z\n', 'b.txt': 'y\n', 'c.log': 'x\n' }],
    ['', 'echo *.txt', { 'a.txt': '', 'b.txt': '' }],
    ['', "echo '*.txt' \"*.txt\"", { 'a.txt': '' }],
    ['', 'echo file?.txt file[12].txt', { 'file1.txt': '', 'file2.txt': '', 'file10.txt': '' }],
    ['', 'wc -l logs/*.log', { 'logs/a.log': '1\n', 'logs/b.log': '1\n2\n' }],
    [T, 'grep zzz; echo $?'],
    [T, 'grep apple && echo yes || echo no'],
    [T, 'grep zzz && echo yes || echo no'],
    [T, 'head -1; head -1'],
    [T, 'sort | head -2; echo ---'],
    [T, 'nosuchcmd; echo $?'],

    // ---- new commands ----
    ['', 'echo hello world'],
    ['', 'echo -n no newline; echo'],
    ['', "echo -e 'a\\tb\\nc'"],
    ['', 'echo "a  b"   c'],
    ['', "printf '%s-%s\\n' a b c d"],
    ['', "printf '%5.2f|%d|%x\\n' 3.14159 42 255"],
    ['', "printf '%-5s|\\n' ab"],
    ['', "printf 'no newline'"],
    ['', "printf '%b\\n' 'x\\ty'"],
    ['', 'seq 5'],
    ['', 'seq 2 5'],
    ['', 'seq 1 3 10'],
    ['', 'seq 5 -2 1'],
    ['', 'seq -w 8 11'],
    ['', 'seq -s, 1 5'],
    ['', 'seq 1 0.5 3'],
    ['', 'seq 0'],
    ['', "seq -f '%03g' 3"],
    ['', 'seq 10 | paste -sd+'],
    ['', 'seq 3 | tee copy.txt | wc -l; cat copy.txt'],
    ['', 'seq 2 | tee -a log.txt; cat log.txt', { 'log.txt': 'old\n' }],
    ['the quick brown fox jumps over the lazy dog', 'fold -w 10'],
    ['the quick brown fox jumps over the lazy dog', 'fold -s -w 10'],
    ['abcdefghijklmnop', 'fold -w 5'],
    ['a\tb\tc', 'fold -w 6'],
    ['name age city\nalice 30 kyiv\nbob 4 lviv', 'column -t'],
    ['name,age\nalice,30\nbob,4', 'column -t -s,'],
    ['a b\n\nccc d', 'column -t'],
    ['', 'comm a.txt b.txt', { 'a.txt': 'apple\nbanana\ncherry\n', 'b.txt': 'banana\ncherry\ndate\n' }],
    ['', 'comm -12 a.txt b.txt', { 'a.txt': 'apple\nbanana\ncherry\n', 'b.txt': 'banana\ncherry\ndate\n' }],
    ['', 'comm -23 a.txt b.txt', { 'a.txt': 'apple\nbanana\ncherry\n', 'b.txt': 'banana\ncherry\ndate\n' }],
    ['', 'comm -3 a.txt b.txt', { 'a.txt': 'apple\nbanana\n', 'b.txt': 'banana\ndate\n' }],
    ['', 'join a.txt b.txt', { 'a.txt': '1 alice\n2 bob\n3 carol\n', 'b.txt': '1 eng\n3 ops\n4 hr\n' }],
    ['', 'join -t, -1 2 -2 1 a.csv b.csv', { 'a.csv': 'alice,d1\nbob,d2\n', 'b.csv': 'd1,Eng\nd2,Ops\n' }],
    ['', 'join -a1 a.txt b.txt', { 'a.txt': '1 alice\n2 bob\n', 'b.txt': '1 eng\n' }],
    ['', 'join -v2 a.txt b.txt', { 'a.txt': '1 alice\n', 'b.txt': '1 eng\n2 ops\n' }],
    ['', 'join -o 2.2,1.2 a.txt b.txt', { 'a.txt': '1 alice\n2 bob\n', 'b.txt': '1 eng\n2 ops\n' }],
    ['', 'paste a.txt b.txt', { 'a.txt': '1\n2\n3\n', 'b.txt': 'x\ny\n' }],
    ['', 'paste -d, a.txt b.txt', { 'a.txt': '1\n2\n', 'b.txt': 'x\ny\n' }],
    ['', 'paste -s a.txt b.txt', { 'a.txt': '1\n2\n', 'b.txt': 'x\ny\n' }],
    ['stdin1\nstdin2', 'paste - a.txt', { 'a.txt': 'x\ny\n' }],

    // ---- sed on files ----
    ['', "sed -i 's/a/A/g' f.txt; cat f.txt", { 'f.txt': 'banana\n' }],
    ['', "sed -i.bak '1d' f.txt; cat f.txt f.txt.bak", { 'f.txt': 'one\ntwo\n' }],
    ['', "sed -n '$p' a.txt b.txt", { 'a.txt': '1\n2\n', 'b.txt': 'x\ny\n' }],
    ['', "sed -s -n '1p' a.txt b.txt", { 'a.txt': '1\n2\n', 'b.txt': 'x\ny\n' }],
    [T, "sed 'y/abc/ABC/'"],
    [T, "sed '2i --- inserted ---'"],
    [T, "sed '$a THE END'"],
    [T, "sed '/apple/c (fruit removed)'"],
    [T, "sed '2,4c [lines 2-4]'"],
    [T, "sed -n '/a/w with_a.txt'; cat with_a.txt"],
    [T, "sed 's/a/A/w changed.txt'; cat changed.txt"],
];
